### PR TITLE
fix(build): dont use `Array.flatMap`

### LINKED ISSUE #568: [Dialog] Modal animation
## ❓Question

How can i animate unmount of Dialog component? I know about react-spring in the docs, but i want to use more lightweight solution

I was trying to animate it like this:
https://codesandbox.io/s/csstransition-component-mi7p3?file=/index.js
but, no luck

https://dev.to/michalczaplinski/super-easy-react-mount-unmount-animations-with-hooks-4foj

### LINKED ISSUE #586: CodeSandbox CI builds don't include JS
This is not related to the components themselves, but rather the Codesandbox PR deployments.

Take a look at https://codesandbox.io/s/hardcore-hertz-fu7d8. Notice that there's an error when importing components from `@reach/tabs` (this applies to all packages).

On further inspection, downloading the package (https://pkg.csb.dev/reach/reach-ui/commit/61bcce10/@reach/tabs") via Codesandbox and opening it reveals that it does not include any JS:

```sh
➜  Downloads ls package
README.md    package.json styles.css
```

I am not sure what the problem here is but it's something we should definitely fix.

### PR DESCRIPTION
**Pull request by raunofreiberg**
Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your request more quickly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code (Compile and run).
- [ ] Add or edit tests to reflect the change (Run with `yarn test`).
- [ ] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [x] Ensure formatting is consistent with the project's Prettier configuration.

This pull request:

- [ ] Creates a new package
- [ ] Fixes a bug in an existing package
- [ ] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [x] Other

<hr />

Closes #586

I figured it's probably more straightforward to just drop `Array.flatMap` for now. We could instead check for `'flatMap' in Array` as well, but I don't see the point.

### CODE REVIEW

File: scripts/build.ts [hunk 1]
```diff
@@ -267,10 +268,10 @@ function createConfigItems(type: any, items: any[]) {
 function mergeConfigItems(type: any, ...configItemsToMerge: any[]) {
   const mergedItems: any[] = [];
 
-  configItemsToMerge.forEach(configItemToMerge => {
+  configItemsToMerge.forEach((configItemToMerge) => {
```
Comment (raunofreiberg) [inline scripts/build.ts:271]: thanks prettier

**Comment by raunofreiberg** [comment]
Yay! The components now work per CodeSandbox build: https://codesandbox.io/s/dark-cloud-m46tz
