### PR TITLE
[menu-button] Fixed popover closing when clicking outside

### LINKED ISSUE #566: [menu-button] Popover does not consistently close when clicking between Menu Buttons
### Current Behavior

reachbug2

### Expected behavior

Dropdown of the previously clicked menu item should always close.

### Reproducible example

https://codesandbox.io/s/inspiring-goodall-02zhd?file=/src/index.js

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Reach Package    |   @reach/menu-button      |        0.10.1     |
| React            |        react, react-dom     |    16.13.1     |
| Browser          |    Chromium     |    81.0.4044.113     |
| Browser          |    Firefox     |    75.0    |
| Assistive tech   |   -      |     -    |
| Node             |    nodejs     |  v13.12.0       |
| npm/yarn         |     yarn    |  1.22.4       |
| Operating System |   macOS      |   10.15.4      |

### PR DESCRIPTION
**Pull request by aganglada**
This PR fixes #566 

Thank you for contributing to Reach UI! Please fill in this template before submitting your PR to help us process your request more quickly.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code (Compile and run).
- [x] Add or edit tests to reflect the change (Run with `yarn test`).
- [x] Add or edit Storybook examples to reflect the change (Run with `yarn start`).
- [x] Ensure formatting is consistent with the project's Prettier configuration.
- [ ] Add documentation to support any new features.

This pull request:

- [ ] Creates a new package
- [x] Fixes a bug in an existing package
- [ ] Adds additional features/functionality to an existing package
- [ ] Updates documentation or example code
- [ ] Other

If creating a new package:

- [ ] Make sure the new package directory contains each of the following, and that their structure/formatting mirrors other related examples in the project:
  - [ ] `examples` directory
  - [ ] `src` directory with an `index.tsx` entry file
  - [ ] At least one example file per feature introduced by the new package
  - [ ] Base styles in a `style.css` file (if needed by the new package)

### CODE REVIEW

**Comment by aganglada** [comment]
@chaance could I get your 👀 here?  🙏

File: packages/menu-button/src/index.tsx [hunk 1]
```diff
@@ -900,30 +900,28 @@ export const MenuPopover = forwardRef<any, MenuPopoverProps>(
...
+          dispatch({ type: CLOSE_MENU, payload: { buttonRef } });
         }
       }
-      window.addEventListener("mousedown", listener);
+      document.addEventListener("mousedown", listener);
+      document.addEventListener("touchstart", listener);
       return () => {
-        window.removeEventListener("mousedown", listener);
+        document.removeEventListener("mousedown", listener);
+        document.removeEventListener("touchstart", listener);
```
Comment (cpmsmith) [inline packages/menu-button/src/index.tsx:922]: The addition of `touchstart` events here means that the popover is closed as soon as you begin scrolling on a touch device. Is this desired?

Comment (aganglada) [reply packages/menu-button/src/index.tsx:922]: I don't think that's a problem. As a user, if you are scrolling you are not really paying attention to the popover anymore right?

**Comment by aganglada** [comment]
@chaance When do you have planned a new release to fix this problem? Thanks for the quick review.

File: packages/menu-button/src/index.tsx (hunk 1 above)
Comment (cpmsmith) [reply packages/menu-button/src/index.tsx:922]: I don't think that's a safe assumption, especially if the menu items overflow the screen.

**Comment by JoshuaKGoldberg** [comment]
Ping @chaance? Sorry if this is bugging you, but is there any visibility into whether there'll be a new version (or even a beta) published soon, please?

**Comment by chaance** [comment]
I'll probably get to it this weekend, got a few more PRs I need to wrap up first. If you need this in the mean time, I'd consider [patch-package](https://www.npmjs.com/package/patch-package).

File: packages/menu-button/src/index.tsx (hunk 1 above)
Comment (chaance) [reply packages/menu-button/src/index.tsx:922]: @cpmsmith You raise a good point. I'm not sure what the answer is but I'll revert this change and open a new issue to consider this case separately.

Comment (cpmsmith) [reply packages/menu-button/src/index.tsx:922]: I think it should be fine to just leave it with `mousedown`, no? Mobile browsers will fire it on any tap, but not scrolling, which is what I'd expect.

Comment (chaance) [reply packages/menu-button/src/index.tsx:922]: There are a few menu button type interactions on iOS that do not close the menu on immediate touch, but they do close it when you start scrolling. There may be cases where you do and don't want this on a web UI, so it may be worth exploring.
